---
title: "Explorer"
format: html
---

```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
dashboardr::.page_config(accessibility = TRUE, inputs = TRUE, crosstab_prefix = "explorer")
```

```{r setup}
#| echo: false
#| warning: false
#| message: false
#| error: false
#| results: 'hide'

# Load dashboardr (includes dplyr, highcharter as dependencies)
library(dashboardr)

# Global chunk options
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  fig.width = 12,
  fig.height = 8,
  dpi = 300
)

# Load data
data <- readRDS('dataset_large_21700obs.rds')

# Data summary
cat('Dataset loaded:', nrow(data), 'rows,', ncol(data), 'columns\n')

```


## GSS Data Explorer



Filter the data using the controls below. All charts update automatically.


```{r}
#| echo: false
#| results: 'asis'
dashboardr::render_input_row(list(
  list(
    input_id = "edu",
    label = "Education Level",
    type = "select_multiple",
    filter_var = "degree",
    options = NULL,
    options_from = "degree",
    default_selected = NULL,
    placeholder = "Select...",
    width = "250px",
    min = 0,
    max = 100,
    step = 1,
    value = NULL,
    show_value = TRUE,
    inline = TRUE,
    stacked = FALSE,
    stacked_align = "center",
    group_align = "left",
    ncol = NULL,
    nrow = NULL,
    toggle_series = NULL,
    override = FALSE,
    labels = NULL,
    size = "md",
    help = NULL,
    disabled = FALSE,
    mt = NULL,
    mr = NULL,
    mb = NULL,
    ml = NULL,
    icons = NULL
  ),
  list(
    input_id = "race",
    label = "Race",
    type = "checkbox",
    filter_var = "race",
    options = NULL,
    options_from = "race",
    default_selected = NULL,
    placeholder = "Select...",
    width = "300px",
    min = 0,
    max = 100,
    step = 1,
    value = NULL,
    show_value = TRUE,
    inline = TRUE,
    stacked = FALSE,
    stacked_align = "center",
    group_align = "left",
    ncol = NULL,
    nrow = NULL,
    toggle_series = NULL,
    override = FALSE,
    labels = NULL,
    size = "md",
    help = NULL,
    disabled = FALSE,
    mt = NULL,
    mr = NULL,
    mb = NULL,
    ml = NULL,
    icons = NULL
  )
), style = "boxed", align = "center")
```


```{r}
#| echo: false
#| results: 'asis'
dashboardr::render_input_row(list(
  list(
    input_id = "sex",
    label = "Gender",
    type = "radio",
    filter_var = "sex",
    options = NULL,
    options_from = "sex",
    default_selected = NULL,
    placeholder = "Select...",
    width = "300px",
    min = 0,
    max = 100,
    step = 1,
    value = NULL,
    show_value = TRUE,
    inline = TRUE,
    stacked = FALSE,
    stacked_align = "center",
    group_align = "left",
    ncol = NULL,
    nrow = NULL,
    toggle_series = NULL,
    override = FALSE,
    labels = NULL,
    size = "md",
    help = NULL,
    disabled = FALSE,
    mt = NULL,
    mr = NULL,
    mb = NULL,
    ml = NULL,
    icons = NULL
  )
), style = "boxed", align = "center")
```

## Results


::: {.panel-tabset}

### Happiness

```{r results}
# Happiness
result <- viz_bar(
  data = data,
  title = "Happiness",
  color_palette = NULL,
  weight_var = NULL,
  x_var = "happy",
  cross_tab_filter_vars = c("degree", "race", "sex")
)

result <- dashboardr:::.embed_cross_tab(result)

result
```


### Political Views

```{r results-2}
# Political Views
result <- viz_bar(
  data = data,
  title = "Political Views",
  color_palette = NULL,
  weight_var = NULL,
  x_var = "polviews",
  cross_tab_filter_vars = c("degree", "race", "sex")
)

result <- dashboardr:::.embed_cross_tab(result)

result
```


:::

